name: oria_pro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  auto_route: ^8.1.3
  dio: ^5.4.1
  curl_logger_dio_interceptor: ^1.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  equatable: ^2.0.5
  path_provider: ^2.1.2
  salomon_bottom_bar: ^3.3.2
  url_launcher: ^6.2.5
  dotted_line: ^3.2.2
  pinput: ^4.0.0
  flutter_typeahead: ^5.2.0
  dropdown_button2: ^2.3.9
  easy_date_timeline: ^1.0.3
  calendar_date_picker2: ^1.0.2
  shared_preferences: ^2.2.2
  hms_room_kit: ^1.1.2
  permission_handler: ^11.3.1
  flutter_rating_bar: ^4.0.1
  html: ^0.15.4
  open_filex: ^4.4.0
  dotted_border: ^2.1.0
  custom_check_box: ^0.0.4
  syncfusion_flutter_charts: ^25.2.3+1
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.1.1
  google_sign_in: ^6.2.1
  change_app_package_name: ^1.1.0
  path: ^1.9.0
  flick_video_player: ^0.8.0
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2
  flutter_facebook_auth: ^6.0.4
  launcher_name: ^1.0.2

dependency_overrides:
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^8.0.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

launcher_name:
  default: "Oria"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-BlackItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-MediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.otf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/Raleway-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Raleway-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Raleway-Thin.ttf
          weight: 100
        - asset: assets/fonts/Raleway-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Marcellus
      fonts:
        - asset: assets/fonts/Marcellus-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
