// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsvfFHOI8pU6M0GFEo0hDZdCZhjd4IYs',
    appId: '1:793225857832:web:9476927b312d6975519e1d',
    messagingSenderId: '793225857832',
    projectId: 'oria-client',
    authDomain: 'oria-client.firebaseapp.com',
    storageBucket: 'oria-client.appspot.com',
    measurementId: 'G-HRZK1LYNWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYP7CCaWIQqF28iMfkOmQL7OeLLsHGP14',
    appId: '1:793225857832:android:848c84a731e15a9e519e1d',
    messagingSenderId: '793225857832',
    projectId: 'oria-client',
    storageBucket: 'oria-client.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy2JIQTvoJbsX6vlZEh7LIqw5GTgPSq2o',
    appId: '1:793225857832:ios:37d82afa811e2a22519e1d',
    messagingSenderId: '793225857832',
    projectId: 'oria-client',
    storageBucket: 'oria-client.appspot.com',
    iosBundleId: 'client.oria.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy2JIQTvoJbsX6vlZEh7LIqw5GTgPSq2o',
    appId: '1:793225857832:ios:f9c680758a9120c0519e1d',
    messagingSenderId: '793225857832',
    projectId: 'oria-client',
    storageBucket: 'oria-client.appspot.com',
    iosBundleId: 'com.example.oriaPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATsvfFHOI8pU6M0GFEo0hDZdCZhjd4IYs',
    appId: '1:793225857832:web:b4eec0d0bec6c1d9519e1d',
    messagingSenderId: '793225857832',
    projectId: 'oria-client',
    authDomain: 'oria-client.firebaseapp.com',
    storageBucket: 'oria-client.appspot.com',
    measurementId: 'G-M3TSBVJYPF',
  );
}
